name: Deploy to AWS S3 and Invalidate CloudFront Cache

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_ORGANIZATION_NAME: ${{ secrets.VITE_ORGANIZATION_NAME }}
          VITE_COGNITO_CLIENT_ID: ${{ secrets.VITE_COGNITO_CLIENT_ID }}
          VITE_COGNITO_URL: ${{ secrets.VITE_COGNITO_URL }}
          VITE_COGNITO_REDIRECT_URL: ${{ secrets.VITE_COGNITO_REDIRECT_URL }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          id-token: write
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: "us-east-1"

      - name: Sync to S3 bucket
        run: aws s3 sync build/ s3://tricker-ui-staging --delete

      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E21Z67OWCUQXXZ --paths "/*"
